- releases/raw.txt
> Simplified & Update Hanime hosts

- releases/hosts
> [ADD] addic7ed.com

- releases/hosts
> add imgur.com, fix #55

- releases/hosts~
Fix #62, maaf lupa ganti nama branch
> add i2 i3 i4 myreadingmanga.info, fix #62

- .editorconfig
- releases/hosts
- releases/hosts.android
- releases/hosts.sfw
- Tambah torrents.io
- Tambah konfigurasi EditorConfig. Banyak diff yang samar di berkas hos dikarenakan banyak spasi putih. Info untuk penyelarasan pengaturan text editor: https://editorconfig.org/
> Tambah torrents.io, dll

- releases/hosts
- releases/hosts.android
> Add host thumbnail.hgamecg.com and nijicollage.xyz

- dev/readme/NETFLIX.md
Menambah tutorial PowerTunnel untuk Netflix.
> Update NETFLIX.md for PowerTunnel Tutorial

- releases/hosts
Biar subtitle bisa di download
> Add dl.opensubtitles.org

- releases/hosts
Issue #115
- Add IP for zenra.net
Issue #116 
- Fix IP for gelbooru.com
- Add IP for img1.gelbooru.com
Issue #117
- Add IP for embed.watchasian.to
> Fixing hosts issues

- releases/hosts
Issue #120 
- Add hosts to charterbate.io
- Add hosts to cityxguide.com
> Resolve Issue #120

- releases/hosts
nambah thubms.redgifs.com mang, soal nya thumbnails nya gk muncul tadi.
> add redgifs

- releases/hosts
A: 
1. minioppai.org
2. porn.com
3. thisvid.com (User : cezary on Discord)
M: 
1. Mengubah blocking ip menjadi 0.0.0.0 dari 127.0.0.1 dikarenakan localhost sering digunakan untuk beberapa aplikasi hosting
2. Mengubah beberapa ip core reddit.com dikarenakan user yang tidak dapat mengakses (***Issue #138***)
3. Menambahkan proxy dari nhentai.net (nhent.ai)
> Update Hosts (Liat di Deksripsi)

- releases/hosts
A : Core domain for redgifs.com
M : redgifs.com main ip
reffered from **Issue #146**
> Update Hosts (Baca Deskripsi)

- releases/hosts
A: javfinder.la / JavFinder
A: findercdn.me / CDN untuk JavFinder
> Add javfinder.la + findercdn.me

- releases/hosts
jangan di merge ya, ini buat issue #162
> update hosts for bebasid

- releases/hosts
172.67.74.156 redgifs.com
13.35.193.77 www.redgifs.com
> Add Redgifs.com

- releases/hosts
Reverts bebasid/bebasid#171
ada duplikasi [redgifs.com] di line terakhir, sebentar nanti diganti ip baru.
> Revert "Add Redgifs.com" dari Pull Requests #171 dan Pembaruan Hosts Terbaru

- releases/hosts
Adding 104.20.1.31 assets-js.blacked.com
99.192.156.43 asiansexdiary.com www.asiansexdiary.com
99.192.156.43 join.asiansexdiary.com
> Update Blacked And Asian Sex Diary

- releases/hosts
107.23.151.94
static.crazyshit.com
> Update IP From Redgifs and Crazyshit

- releases/hosts
Selain pembaruan IP, ternyata untuk domain `mangareader.net` dan `www.mangareader.net` menggunakan alamat yang berbeda, jadi saya pisahkan saja.
> M: Mangareader.net (#207)

- releases/hosts
> Add downloadgameps3.com

- releases/hosts
> Add bfst.xyz

- releases/hosts
Related issue: https://github.com/bebasid/bebasid/issues/232
Lookup result: [Here](https://imgur.com/a/Zw3Q6OC)
> feat(hosts): updated Omegle IP addresses and its subdomains

- releases/hosts
> Add jkforum.net

- releases/hosts
Added support for Reddit's latest event (Layer Season 2), as seen [here](https://www.reddit.com/r/Layer/).
> A: layers-svc.reddit.com

- releases/hosts
Delete leetcode in host because it cause the website cannot load at all. removing leetcode from the host seems to solve it 
ISP : indihome
> D: leetcode.com

- releases/hosts
TL:DR: ssoap2day.to adalah situs web yang memungkinkan siapa saja untuk menonton film apapun.
Launchpad ditambahkan atas request: https://github.com/bebasid/bebasid/issues/319
> Add ssoap2day.to & launchpad.binance.com

- releases/hosts
codeply.com update ke ip baru.
> ganti codeply

- releases/hosts
Menambahkan situs **pusatporn18.com**
IP diambil menggunakan DNS cloudflare
> A: pusatporn18.com

- releases/hosts
**Add**
- Semprot.com
- Idlix.xyz
**Fix**
- Semprotku (New IP)
- Idlix (Unable to load video when idlix.xyz unable to reach)
**Remove**
- Extra space in some lines
> Fix semprot (Close #383) & Idlix

- releases/hosts
Jika Diizinkan Saya Menambahkan situs manhuascan.com | IP diambil menggunakan DNS cloudflare | Terimakasih
[![2021-08-27-124525-618x125-scrot.png](https://i.postimg.cc/v84T9bgW/2021-08-27-124525-618x125-scrot.png)](https://postimg.cc/3WH3QMZR)
> Menambahkan: manhuascan.com

- releases/hosts
> A: himovies.to

- releases/hosts
Di ambil menggunakan OpenVPN-tcpvpn server Indonesia.
Modify Nutaku.net dan subdomain network.nutaku.com
> M: nutaku.net

- releases/hosts
Informasi tambahan:
- OS: Windows 10 20H2 / Manjaro 21.1.6 Pahvo
- TKP: Sulawesi Selatan
- Provider: Indihome
> A: hentaiff.com

- releases/hosts
Menambahkan domain binance.org ke host
> binance.org

- releases/hosts
Informasi tambahan:
- OS: Windows 10 20H2 / Manjaro 21.1.6 Pahvo
- TKP: Sulawesi Selatan
- Provider: Indihome
> A: virtamate.com

- releases/hosts
Di ambil menggunakan OpenVPN-tcpvpn server Indonesia.
Modify hitomi.la dan beberapa subdomainnya.
> M: hitomi.la

- releases/hosts
Co-authored-by: gvoze32 <gvoze32@gmail.com>
> m: change junmeitu.com ip domain

- README.en.md
- README.md
saya memperbaiki beberapa kata di Readme, terimakasih telah membaca pull request saya!
> M : Readme.md

- dev/readme/USAGE.md
akan di merge kan setelah semua centang ini sudah selesai
boleh kalo mau bantu benerin typo & tambahin langkah2 yang mudah & gampang dibaca
> improve grammar & tutorials

- releases/hosts
Memperbaiki domain yang tidak valid.
> Fix malformarted domains

- releases/hosts
> fix: tambah host kemono

- releases/hosts
> fix: update host bato.to

- releases/hosts
> feat: hltv.org

- releases/bebasid.sh
Memperbaiki kesalahan pada penulisan uninstall
> Memperbaiki Kesalahan Doc/Help

- README.md
Changes:
Redo the look for Badge
Stop using large social media banners
Put DPI notice in a dropdown
> Make README less cluttered

- releases/hosts
<p align="center">
<kbd>
</kbd>
Menambahkan situs bybit.com/www.bybit.com karena situs ini tidak bisa dibuka melewati chrome/browser lainnya ketika tidak menggunakan dns | IP diambil menggunakan DNS cloudflare dengan menggunakan tools <a href="https://github.com/mr-karan/doggo">doggo</a>
> A: bybit.com/www.bybit.com

- releases/hosts
> Update A: yande.re/www.yande.re

- releases/hosts
change ip: 
- yande.re /www (198.251.89.183)
- assets.yande.re (198.251.88.76)
- files.yande.re (198.251.88.76)
> Update A: yande.re
