bebasid/bebasid

raw.txt
Cara generate-nya gimana ya?
Kalau bisa ditambahkan script untuk itu, biar mudah :)
=> Add more domain on Reddit

raw.txt
Reverts apkcube/blockhostid#22
=> Revert "Add more domain on Reddit"

raw.txt
fanfiction.net diblokir oleh ISP Telkomsel meskipun tidak ada di database Trust+.
=> Add fanfiction.net

hosts
Social Networking Site for BDSM
=> Adding Fetlife.com

hosts
Add `151.101.201.140 mod.reddit.com` to Reddit section.
=> Add mod.reddit.com

hosts
=> Tambah player.hanime.tv

raw.txt
added and simplified rule34.xxx
```
104.25.223.113 rule34.xxx www.rule34.xxx hk.rule34.xxx img.rule34.xxx
185.180.221.231 webmc.rule34.xxx
89.233.106.186 webm.rule34.xxx
```
=> Added hk.rule34.xxx and simplified rule34 section

raw.txt
Added:
- BEEG.COM
Fixed:
- hentai-for.me 
- jav.guru
=> Added & fixed some hosts

raw.txt
=> Add v.redd.it

raw.txt
Host Added:
```
- s.reddit.com
- external-preview.redd.it
- preview.redd.it
- styles.redditmedia.com
- gql.reddit.com
```
=> Added a bunch of reddit hosts

raw.txt
=> added hkwebm.rule34.xxx

raw.txt
```
190.2.148.183 wwebm.rule34.xxx
```
=> added wwebm.rule34.xxx

raw.txt
```
- Myhentai Galleries
- Shentai.org
- comdotgame
- SWFCHAN
```
=> Added moar sites

INSTALL.md
Add "How to Install BEBASID Command for Linux"
Ketentuan Pull Request:
- Silahkan untuk mengubah file raw.txt saja 
- Jika sebelumnya terdapat pull request, silahkan ubah file yang ada di pull tersebut
- Untuk format pull khusus bug, silahkan tambahkan line baru atau sekedar edit di bagian ip/domainnya saja
- Untuk format pull khusus add, silahkan tambahkan line baru lengkap dengan nama website diatasnya, seperti yang sudah ada
Terima kasih sudah berkontribusi dalam pengembangan komunitas aplikasi ini, semoga dapat bermanfaat bagi semua yang memakainya.
=> v6.9 - FREEDOM! v2

bebasid.sh
BEBASID Linux Command
Bash ini saya buat agar pengguna tidak repot-repot melakukan banyak prosedur untuk membuka akses blokiran website seperti mencari IP Address serta mengedit file /etc/hosts. Semua hanya dilakukan dengan command 'bebasid unblock websiteyangingindiunblock.com'. Selain hal itu, masih banyak fitur-fitur untuk penggunaan BEBASID.
Fitur-fitur yang tersedia:
1. Install BEBASID;
2. Update BEBASID;
3. Uninstall BEBASID;
4. Unblock Website;
5. Block Website;
6. Fix Error yang disebabkan oleh file "/etc/hosts/".
Saya sebenarnya ingin menerapkan agar dapat menghapus website yang ter-list di file hosts serta jika update BEBASID, tidak perlu untuk menambah manual kembali website yang sebelumnya diunblock. Saya sudah memikirkan pseudocode untuk hal itu, namun saya tidak dapat …
=> v1.0 FREEDOM! BETA 1

scanner.php
BEBASID Domain2IPScanner
Cara pemakaian:
1. Install PHP-CLI dan DNSUTILS/BINDUTILS;
2. Buat file txt berisi list domain yang ingin diunblock;
3. Scan dengan command "php unblock fileyanginginandaunblock.txt" bisa juga di screen;
4. Tunggu hingga selesai;
5. File hasil scan "hosts-fileyanginginandaunblock.txt".
Untuk baris file lebih dari 100000:
1. Jika lines file txt lebih dari 100000, harus displit agar tidak terjadi timeout, contohnya, list file yang ingin diunblock ada 1 juta, nah, file tersebut displit menjadi 100000 line per file ("split -l 100000 fileyangingindiunblock.txt"), jika tidak, langsung menuju langkah no 6;
2. Setelah displit, maka akan muncul file "xaa" "xab" "xac" dst, nah, untuk mempercepat silahkan gunakan screen untuk scan per file ("screen php unblock.php xaa" lalu …
=> v1.0 - FREEDOM! v1

bebasid.sh
Changelog
1. Fix missing function in block command
2. Add block/unblock record (if you update BEBASID, the website that you unblock will not be deleted or still exist)
Belum menambahkan fungsi mengecek duplicate line (if exist) dengan alasan if exist akan turut menghapus subdomain atau tidak.
Ketentuan Pull Request:
- Silahkan untuk mengubah file raw.txt saja 
- Jika sebelumnya terdapat pull request, silahkan ubah file yang ada di pull tersebut
- Untuk format pull khusus bug, silahkan tambahkan line baru atau sekedar edit di bagian ip/domainnya saja
- Untuk format pull khusus add, silahkan tambahkan line baru lengkap dengan nama website diatasnya, seperti yang sudah ada
Terima kasih sudah berkontribusi dalam pengembangan komunitas aplikasi ini, semoga dapat bermanfaat bagi semua yang …
=> v1.0 - Release Dove

raw.txt
```
151.101.53.140 www.reddit.com
151.101.53.140 gql.reddit.com
```
=> Update some reddit hosts

raw.txt
```
151.101.53.140 www.redditstatic.com
151.101.53.140 i.redd.it
```
=> added more reddit hosts

README.md
Edotensei link yang mati
Ehehehehe
=> pembaruan struktur repository

dev/readme/NETFLIX.md
Dokumentasi di [NETFLIX.md](https://github.com/gvoze32/bebasid/blob/master/dev/readme/NETFLIX.md) belum disesuaikan dengan perubahan struktur repository.
Saya juga ubah tautan di dokumentasi menjadi tautan relatif, supaya repository fork tidak bergantung terhadap repository utama.
Tambahan: standardisasi tutorial di NETFLIX.md
=> INSTALL.md -> USAGE.md di NETFLIX.md

releases/raw.txt
```
[F95ZONE.TO]
104.26.6.12 f95zone.to www.f95zone.to static.f95zone.to attachments.f95zone.to 
```
=> Sedikit update

releases/raw.txt
```
104.28.8.124 cdn.freeanimehentai.net
104.28.9.124 i2.freeanimehentai.net
```
satu host ketinggalan kemaren.
=> hanime update

releases/raw.txt
=> add terk.nl and 141jav.com

releases/raw.txt
=> add psarips.one and fap-nation.com
